resources:
  - name: api_in_runs_propertyBag_01
    type: PropertyBag
    configuration:
      pipelines: "user_in"

  - name: api_out_runs_propertyBag_02
    type: PropertyBag
    configuration:
      pipelines: "user_out"
      
pipelines:
  - name: api_runs
    steps:
      - name: api_runs_step
        type: Bash
        configuration:
          inputResources:
            - name: api_in_runs_propertyBag_01
          outputResources:
            - name: api_in_runs_propertyBag_01
        execution:
          onExecute:
            - write_output api_out_runs_propertyBag "pipelines=$run_id"
