# resources:
#   - name: myGitRepo
#     type: GitRepo
#     configuration:
#       gitProvider: raksha78_github
#       path: raksha78/jfrog-pipelines-simple-example
#       branches:
#         include: master      
pipelines:  
  - name: basic_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo           
        execution:
          onExecute:
            - echo "hello"
     
           
