pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Bash
        configuration:
          runtime:
            type: host
        execution:
          onExecute:
            - echo lol
